#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo $'\nPlease be patient 😄 Your code is being checked before commiting 🚀'

npx vite build
if [ $? -ne 0 ]; then
  echo $'There were some errors ❌ Fix them and try again 🔧\n'
  exit 1
fi

npx lint-staged
